### PR TITLE
Stating VS 2015 is a supported environment

### PR DESCRIPTION
**Pull request by ceddlyburge**
Hi Daniel

I've been using this plugin (without any changes) in vs 2015 without problems, so I've just added 2015 the the manifest so that it is installable.

Cheers

Cedd

### CODE REVIEW

**Comment by vinntreus** [comment]
Hi,

Cool! Thanks for contributing, I'll try and manually change the vsix package and upload it so it will be available in Visual Studio gallery.

**Comment by ceddlyburge** [comment]
Thanks Daniel, we're using it in my company to try and reduce compile times
at the moment, so its possible I'll get time to do some other bits.

Cheers

Cedd

On Wed, Dec 23, 2015 at 12:23 PM, Daniel Vinntreus <notifications@github.com

**Comment by vinntreus** [comment]
You are more than welcome, I have just updated the package in Visual Studio Gallery (https://visualstudiogallery.msdn.microsoft.com/b0c87e47-f4ee-4935-9a59-f2c81ce692ab) so it should be available to find in Visual Studio shortly. 
I currently only have access to a mac, could you verify that it works?

**Comment by ceddlyburge** [comment]
Hi Daniel, I have installed the new version and it works for me without any
problems.

Cheers

Cedd

On Wed, Dec 23, 2015 at 12:58 PM, Daniel Vinntreus <notifications@github.com

**Comment by ceddlyburge** [comment]
Hi Daniel

I am having some trouble compiling the solution, I think because I don't
have the relevant password for the key.pfx file.

*Error        Cannot import the following key file: key.pfx. The key file
may be password protected. To correct this, try to import the certificate
again or manually install the certificate to the Strong Name CSP with the
following key container name: VS_KEY_DD6232E978A6770B    BuildMonitor
    *

Could you let me have it?

Thanks

Cedd

**Comment by vinntreus** [comment]
Sorry, I cannot remember the password.. I think you can modify the project-files (BuildMonitor and BuildMonitorPackage), and remove strong signing and then reload the project in VS in order to compile.
Try and remove the property groups with "SignAssembly" and "AssemblyOriginatorKeyFile" and the files "key.snk" and "key.pfx"

**Comment by ceddlyburge** [comment]
Hi Daniel

Thanks for this.

I've signed with a new key file, I'm tell you the details when i do a pull
request.

I'm adding a form that will initially show a monthly breakdown of build
times by solution.

Cheers

Cedd

**Comment by ceddlyburge** [comment]
Hi Daniel, you don't seem to be very impressed with my latest pull request,
is there a problem with it?

Cheers

Cedd

**Comment by vinntreus** [comment]
Hi,

Sorry I hade totaly missed this. I'm on vacation now, will try and have a look next week.

/Daniel

> 01 Apr 2016 kl. 15:32 skrev ceddlyburge <notifications@github.com>:
> 
> Hi Daniel, you don't seem to be very impressed with my latest pull request,
> is there a problem with it?
> 
> Cheers
> 
> Cedd
> 
> On Sat, Jan 23, 2016 at 2:22 PM, Cedd Burge <ceddlyburge@googlemail.com>
> wrote:
> 
> > Hi Daniel
> >
> > Thanks for this.
> >
> > I've signed with a new key file, I'm tell you the details when i do a pull
> > request.
> >
> > I'm adding a form that will initially show a monthly breakdown of build
> > times by solution.
> >
> > Cheers
> >
> > Cedd

**Comment by ceddlyburge** [comment]
Ok, don't rush back :)

**Pull request merged**
